services:
  vm21:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vm21
    restart: unless-stopped
    ports:
      - "5210:3000"
    volumes:
      - ./server:/app/server
      - /app/node_modules
      - /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket
    privileged: true
    group_add:
      - "101"